num_envs: 8
num_steps: 100 # not used, maximum time steps per training episode
batch_size: 2048 # num_envs * num_steps
num_minibatches: 32
minibatch_size: 32 # batch_size / num_minibatches
num_iterations: 800 # number of training iterations
total_timesteps: 1000000 # not used

# NN architecture

grid: 3 # number of grid intervals
k: 2 # spline order

critic_hidden_sizes: []


actor_hidden_sizes: []

update_epochs: 4
anneal_lr: true
capture_video: false
clip_coef: 0.2
clip_vloss: true
cuda: true
ent_coef: 0.0
env_config: configurations/bicycle_conf.yaml
env_id: pilot_gym/RacingEnv-v0
exp_name: ppo_continuous_action_kan
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0005
max_grad_norm: 0.5
norm_adv: true
save_model: true
seed: 1
target_kl: null
torch_deterministic: true
vf_coef: 0.5
